import{useState}from"react"
const C={cepeda:{name:"Iván Cepeda",short:"Cepeda",tag:"Izquierda",color:"#e84c3d",emoji:"🔴"},lopez:{name:"Claudia López",short:"C. López",tag:"Centro-izq.",color:"#9b59b6",emoji:"🟣"},fajardo:{name:"Sergio Fajardo",short:"Fajardo",tag:"Centro",color:"#27ae60",emoji:"🟢"},valencia:{name:"Paloma Valencia",short:"Valencia",tag:"Derecha",color:"#2980b9",emoji:"🔵"},espriella:{name:"De la Espriella",short:"Espriella",tag:"Derecha ind.",color:"#e67e22",emoji:"🟠"}}
const Q=[{t:"💸 La plata",p:"Si el gobierno tuviera plata extra, ¿qué debería hacer?",o:[{x:"Dársela a los que menos tienen.",s:{cepeda:3,lopez:1}},{x:"Invertirla en educación y hospitales.",s:{fajardo:3,lopez:1}},{x:"Pagar deudas y no endeudarnos más.",s:{espriella:3,valencia:2}},{x:"Bajar impuestos para crear empleo.",s:{valencia:3,espriella:1}}]},{t:"🔫 Seguridad",p:"¿Cómo le metemos mano a los grupos violentos?",o:[{x:"Hablando y ofreciéndoles salidas pacíficas.",s:{cepeda:3}},{x:"Policía y ejército, pero con oportunidades.",s:{fajardo:3,lopez:1}},{x:"Tratarlos como criminales, sin negociar.",s:{lopez:3,espriella:1}},{x:"Mano durísima, cero contemplaciones.",s:{valencia:3,espriella:2}}]},{t:"🏥 Salud",p:"¿Cómo debería funcionar la salud?",o:[{x:"El Estado maneja todo, salud gratis.",s:{cepeda:3}},{x:"Que funcione bien con EPS y clínicas.",s:{valencia:3,espriella:2}},{x:"Mejorar lo que hay sin dañar lo que funciona.",s:{fajardo:2,lopez:2}},{x:"Quitarles poder a los que se roban la plata.",s:{lopez:3,cepeda:1}}]},{t:"☮️ La paz",p:"Con los grupos armados que quedan…",o:[{x:"Negociar y buscarles salida, así tome años.",s:{cepeda:3}},{x:"Que dejen las armas primero.",s:{espriella:2,fajardo:1}},{x:"Nada de diálogo: el ejército que los acabe.",s:{valencia:3,espriella:2}},{x:"Combatirlos, pero darles segunda oportunidad.",s:{fajardo:2,lopez:2}}]},{t:"📚 Educación",p:"¿En qué gastar más para que los jóvenes tengan futuro?",o:[{x:"Universidad gratis para quien no puede.",s:{cepeda:3,lopez:1}},{x:"Colegios públicos tan buenos como privados.",s:{fajardo:3}},{x:"Cursos técnicos para salir con un oficio.",s:{fajardo:2,lopez:1,valencia:1}},{x:"Familias eligen: colegios con vouchers.",s:{valencia:2,espriella:2}}]},{t:"⚖️ Desigualdad",p:"Unos pocos tienen mucho y la mayoría poco. ¿Qué hacemos?",o:[{x:"Cobrarles más a ricos, darles más a pobres.",s:{cepeda:3}},{x:"Acabar con la corrupción que roba la plata.",s:{lopez:3,fajardo:1}},{x:"Que la economía crezca y llegue a todos.",s:{valencia:2,espriella:2}},{x:"Igual educación y oportunidades desde chiquitos.",s:{fajardo:3,lopez:1}}]}]
const win=s=>Object.entries(s).sort((a,b)=>b[1]-a[1])[0][0]
const rank=s=>{const m=Math.max(...Object.values(s));return Object.entries(s).sort((a,b)=>b[1]-a[1]).map(([k,v])=>({k,p:m>0?Math.round(v/m*100):0}))}
export default function App(){
const[sc,setSc]=useState("home")
const[nm,setNm]=useState("")
const[ag,setAg]=useState("")
const[qi,setQi]=useState(0)
const[pts,setPts]=useState({cepeda:0,lopez:0,fajardo:0,valencia:0,espriella:0})
const[ch,setCh]=useState(null)
const[res,setRes]=useState(null)
const BG={background:"#0a0a0f",minHeight:"100vh",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",padding:"24px 16px 64px",fontFamily:"sans-serif",color:"#f0eee8"}
const CARD={background:"#13131c",border:"1px solid #1e1e2e",borderRadius:22,padding:"28px 24px",width:"100%",maxWidth:500,boxSizing:"border-box"}
const BTN={background:"#f5c842",color:"#09090f",border:"none",padding:"13px 28px",borderRadius:50,fontFamily:"sans-serif",fontSize:14,fontWeight:700,cursor:"pointer",display:"block",width:"100%",marginTop:14,boxSizing:"border-box"}
const INP={width:"100%",background:"#09090f",border:"1.5px solid #1e1e2e",borderRadius:12,padding:"12px",color:"#f0eee8",fontSize:14,marginTop:6,marginBottom:14,boxSizing:"border-box"}
function pick(i){setCh(p=>p===i?null:i)}
function next(){if(ch===null)return;const o=Q[qi].o[ch];const n={...pts};Object.entries(o.s||{}).forEach(([k,v])=>{n[k]=(n[k]||0)+v});setPts(n);setCh(null);if(qi+1>=Q.length){setRes({nm:nm.trim(),ag:ag.trim(),w:win(n),all:rank(n)});setSc("result")}else setQi(q=>q+1)}
function go(){if(!nm.trim()||!ag.trim())return;setQi(0);setPts({cepeda:0,lopez:0,fajardo:0,valencia:0,espriella:0});setCh(null);setSc("quiz")}
const Logo=()=><div style={{textAlign:"center",marginBottom:20}}><div style={{fontSize:11,fontWeight:700,letterSpacing:"0.15em",color:"#f5c842",textTransform:"uppercase",marginBottom:4}}>🇨🇴 Colombia 2026</div><div style={{fontSize:32,fontWeight:900,color:"#f0eee8",lineHeight:1}}>ENCUÉSTATE</div><div style={{fontSize:13,color:"#555",marginTop:4}}>Descubrí con quién pensás más parecido</div></div>
if(sc==="home")return(<div style={BG}><Logo/><div style={CARD}><label style={{color:"#444",fontSize:11,textTransform:"uppercase",letterSpacing:"0.08em"}}>Tu nombre</label><input style={INP} placeholder="Ej: Carlos" value={nm} onChange={e=>setNm(e.target.value)}/><label style={{color:"#444",fontSize:11,textTransform:"uppercase",letterSpacing:"0.08em"}}>Tu edad</label><input style={{...INP,marginBottom:0}} placeholder="Ej: 34" type="number" value={ag} onChange={e=>setAg(e.target.value)}/><button style={{...BTN,opacity:(nm.trim()&&ag.trim())?1:0.4}} onClick={go} disabled={!nm.trim()||!ag.trim()}>Empezar el quiz →</button></div><p style={{color:"#2a2a3a",fontSize:11,marginTop:20,textAlign:"center"}}>Hecho por <a href="https://www.instagram.com/anderrh" target="_blank" rel="noreferrer" style={{color:"#f5c842",textDecoration:"none"}}>@anderrh</a> · Solo orientativo</p></div>)
if(sc==="quiz"){const q=Q[qi];return(<div style={BG}><div style={CARD}><div style={{display:"flex",justifyContent:"space-between",marginBottom:6}}><span style={{color:"#444",fontSize:11}}>{qi+1} de {Q.length}</span><span style={{color:"#444",fontSize:11}}>{Math.round(qi/Q.length*100)}%</span></div><div style={{height:4,background:"#1a1a28",borderRadius:2,overflow:"hidden",marginBottom:20}}><div style={{width:`${Math.round(qi/Q.length*100)}%`,height:"100%",background:"#f5c842",borderRadius:2}}/></div><div style={{color:"#f5c842",fontSize:11,fontWeight:700,textTransform:"uppercase",marginBottom:8}}>{q.t}</div><h2 style={{fontSize:18,lineHeight:1.3,marginBottom:20}}>{q.p}</h2>{q.o.map((o,i)=>{const s=ch===i;return(<button key={i} onClick={()=>pick(i)} style={{background:s?"#f5c84212":"#0d0d16",border:s?"1.5px solid #f5c842":"1.5px solid #1e1e2e",borderRadius:14,padding:"13px 15px",color:s?"#f0eee8":"#b0aead",fontFamily:"sans-serif",fontSize:13,cursor:"pointer",display:"flex",alignItems:"flex-start",gap:12,width:"100%",marginBottom:10,textAlign:"left",boxSizing:"border-box"}}><span style={{background:s?"#f5c842":"#1e1e2e",color:s?"#09090f":"#444",width:26,height:26,borderRadius:"50%",display:"flex",alignItems:"center",justifyContent:"center",fontSize:11,fontWeight:700,flexShrink:0}}>{["A","B","C","D"][i]}</span>{o.x}</button>)})}{ch!==null&&<p style={{textAlign:"center",fontSize:11,color:"#555",marginTop:4}}>¿Te equivocaste? Toca otra opción.</p>}<button onClick={next} disabled={ch===null} style={{...BTN,opacity:ch!==null?1:0.25}}>{qi+1===Q.length?"Ver mi resultado ✦":"Siguiente →"}</button></div></div>)}
if(sc==="result"&&res){const c=C[res.w];const wt=encodeURIComponent(`🗳️ Hice el quiz ENCUÉSTATE 2026 y pensás más parecido a: ${c.emoji} ${c.name}\n¿Y vos? Hacelo acá → ${window.location.href}`);return(<div style={BG}><div style={CARD}><Logo/><p style={{textAlign:"center",color:"#555",fontSize:12,marginBottom:4}}>¡Listo, {res.nm}! 👋</p><h2 style={{textAlign:"center",marginBottom:14,fontSize:20}}>Pensás más parecido a…</h2><div style={{border:`2px solid ${c.color}`,background:`${c.color}18`,borderRadius:16,padding:"22px",textAlign:"center",marginBottom:20}}><div style={{fontSize:44}}>{c.emoji}</div><div style={{fontWeight:900,fontSize:24,color:c.color,marginTop:6}}>{c.name}</div><div style={{fontSize:12,color:"#666",marginTop:4}}>{c.tag}</div></div><p style={{color:"#444",fontSize:11,textTransform:"uppercase",letterSpacing:"0.08em",marginBottom:10}}>Tu afinidad con todos</p>{res.all.map(({k,p})=>(<div key={k} style={{display:"flex",alignItems:"center",gap:10,marginBottom:8}}><span style={{fontSize:12,minWidth:80,color:C[k].color,fontWeight:700}}>{C[k].short}</span><div style={{flex:1,height:7,background:"#1a1a28",borderRadius:3,overflow:"hidden"}}><div style={{width:`${p}%`,height:"100%",background:C[k].color,borderRadius:3}}/></div><span style={{fontSize:11,color:"#555",minWidth:30,textAlign:"right"}}>{p}%</span></div>))}<a href={`https://wa.me/?text=${wt}`} target="_blank" rel="noreferrer" style={{background:"#25D366",color:"#fff",border:"none",padding:"13px 28px",borderRadius:50,fontFamily:"sans-serif",fontSize:14,fontWeight:700,cursor:"pointer",display:"block",width:"100%",marginTop:20,textAlign:"center",textDecoration:"none",boxSizing:"border-box"}}>📲 Compartir por WhatsApp</a><div style={{marginTop:20,padding:"16px",background:"#0d0d16",borderRadius:16,border:"1px solid #1e1e2e",textAlign:"center"}}><p style={{color:"#555",fontSize:12,marginBottom:12}}>¿Te gustó el quiz? Seguime en Instagram 👇</p><a href="https://www.instagram.com/anderrh" target="_blank" rel="noreferrer" style={{display:"inline-flex",alignItems:"center",gap:8,background:"linear-gradient(45deg,#f09433,#e6683c,#dc2743,#cc2366,#bc1888)",color:"#fff",padding:"11px 22px",borderRadius:50,textDecoration:"none",fontSize:13,fontWeight:700}}>📸 @anderrh</a></div><button style={{background:"transparent",color:"#333",border:"none",fontSize:12,cursor:"pointer",marginTop:14,display:"block",width:"100%",textAlign:"center"}} onClick={()=>{setNm("");setAg("");setSc("home")}}>↩ Hacer de nuevo</button></div></div>)}
return null
}
